package-lock.json, src/routes/api/subscribeKlaviyo.server.ts
Reverts SuavecitoInc/suavecito-us-es#21
=> Revert "fix"

src/components/global/Footer.server.tsx, src/components/global/FooterMenu.client.tsx, src/components/sections/footer-sections/SubscribeEmail.tsx, src/routes/api/subscribeKlaviyo.server.ts
- Fixed invalid element type on default export due to vite production
=> Fix phone input

src/components/elements/Button.tsx, src/components/elements/Divider.tsx, src/components/global/Header.client.tsx, src/components/global/Layout.server.tsx, src/components/product/ProductOptions.client.tsx, src/components/product/ProductOptionsVariantForm.client.tsx, src/components/product/ProductSectionContentGrid.server.tsx, src/components/product/ProductSectionHowItLooks.server.tsx, src/components/product/ProductSectionHowTo.server.tsx, src/components/product/ProductSectionHowToMultipleImages.server.tsx, src/components/product/index.server.ts, src/components/templates/index.server.ts, src/components/templates/product-metafield-spb-template.server.tsx, src/data/brands.ts, src/lib/suavecito-fragments.ts, src/routes/products/premium-blends-beard-oil.server.tsx, src/routes/products/premium-blends-hair-pomade.server.tsx, src/routes/products/premium-blends-matte-pomade.server.tsx
- Added SPB Product Templates
- Updated product components to handle SPB theme
=> Spb products

src/components/product/ProductSectionHowTo.server.tsx, src/components/product/ProductSectionKitIncludes.server.tsx, src/components/product/index.server.ts, src/components/templates/index.server.ts, src/components/templates/product-kit-item-template.server.tsx, src/lib/suavecito-fragments.ts, src/routes/products/mens-hair-kit.server.tsx, src/styles/suavecito.css
=> Kit package template

src/routes/products/[handle].server.tsx
- Does not display Product Options Form if Product Type is FGWP
- If product has no Features filled out, display description below Options, else display in tabs
=> Hide Add to Cart + Options on FGWP Products

README.md, src/components/product/PomadeCompareChart.server.tsx, src/components/product/ProductMetafieldImages.client.tsx, src/components/product/ProductOptionsVariantForm.client.tsx, src/components/product/ProductSectionContentGrid.server.tsx, src/components/product/ProductSectionGetInspired.client.tsx, src/components/product/ProductSectionHowItLooks.server.tsx, src/components/product/ProductSectionHowTo.server.tsx, src/components/product/ProductSectionHowToMultipleImages.server.tsx, src/components/product/ProductSectionInfoTabs.client.tsx, src/components/product/ProductSectionKitIncludes.server.tsx, src/components/product/ProductSectionYouMayAlsoLike.server.tsx, src/components/sections/BestSellers.server.tsx, src/components/templates/product-kit-item-template.server.tsx, src/components/templates/product-metafield-colors-get-inspired-template.server.tsx, src/components/templates/product-metafield-get-inspired-template.server.tsx, src/components/templates/product-metafield-pomade-template.server.tsx, src/components/templates/product-metafield-spb-template.server.tsx, src/components/templates/product-metafield-template.server.tsx, src/data/pomade-chart-es.ts, src/lib/suavecito-fragments.ts, src/locale/product.ts, src/routes/api/subscribeKlaviyo.server.ts, src/routes/index.server.tsx, src/routes/products/[handle].server.tsx, vite.config.ts
- Tried to use env variable to set language since hooks don't work outside components, so far have failed, can't seem to access public env vars in production. Using locale and hardcoding outside of components, until I can figure out whats wrong.
=> Metafield es

src/components/account/AccountCreateForm.client.tsx, src/components/account/AccountLoginForm.client.tsx, src/components/account/AccountRecoverForm.client.tsx, src/components/elements/Button.tsx, src/components/product/ProductOptionsVariantForm.client.tsx, src/lib/suavecito-fragments.ts, src/routes/account/login.server.tsx, src/routes/account/recover.server.tsx, src/routes/account/register.server.tsx
=> Login / Register / Recover - basic styles + transaltions

src/components/cart/CartFreeGiftWithPurchase.client.tsx, src/hooks/useFreeGiftWithPurchase.tsx, src/styles/suavecito.css
- Updated FGWP styles
- Added product card disabled on product unavailable
- Moved add gift button to its own component for re-usability
=> Fgwp styles

src/components/FreeGiftProvider/FreeGiftProvider.client.tsx, src/components/FreeGiftProvider/context.tsx, src/components/FreeGiftProvider/hooks.client.tsx, src/components/FreeGiftProvider/index.ts, src/components/FreeGiftProvider/types.ts, src/components/cart/CartEmpty.client.tsx, src/components/cart/CartFreeGiftWithPurchase.client.tsx, src/components/cart/CartPageDetails.client.tsx, src/data/free-gift-with-purchase.ts, src/data/pomade-chart-es.ts, src/hooks/index.ts, src/routes/cart.server.tsx
- moved FGWP logic / state from custom hook to context
- fixed empty cart `continue shopping` button
=> Moved use Free Gift With Purchase from hook to context

src/components/templates/product-kit-item-template.server.tsx, src/routes/products/[handle].server.tsx, src/styles/suavecito.css
- added basic styles for dangerously set html
=> Updated dangerously set html (p, ul, li) styles

src/components/cards/ProductGridItem.client.tsx, src/components/cards/VariantGridItem.client.tsx, src/components/collection/FeaturedProductGrid.server.tsx, src/components/elements/Badge.tsx, src/components/elements/index.ts, src/components/product/ProductOptionsVariantForm.client.tsx
- Created `Badge` component
- Fixed types in collection product grid components
=> Sale badge

package-lock.json, package.json
#Changes
- Updated `@shopify/cli and @shopify/cli-hydrogen
Had an error on every build. Updated packages, removed package-lock.json, re-installed node_modules.
=> Test Hydrogen Update

index.html, src/components/DefaultSeo.server.tsx, src/components/product/ProductImages.client.tsx, src/components/product/ProductMetafieldImages.client.tsx
- Removed redundant checks on product metafield images. Still need to remove commented out props.
- Added robots no-index
=> Fix product images

src/components/DefaultSeo.server.tsx, src/components/cart/CartDetails.client.tsx, src/components/global/Header.client.tsx, src/routes/index.server.tsx, src/routes/robots.txt.server.ts
- Removed necessary / incomplete components
=> Disable non working features

src/data/home-page-es.ts
=> Updated Home Page Banner

src/components/templates/collection-featured-variants.server.tsx, src/data/collection-featured-banners.ts, src/routes/collections/collaborations.server.tsx, src/routes/collections/suavecito-x-cristocat.server.tsx, src/routes/collections/suavecito-x-fast-and-furious.server.tsx, src/routes/collections/suavecito-x-felix-the-cat-vol-2.server.tsx, src/routes/collections/suavecito-x-loser-machine.server.tsx, src/routes/collections/suavecito-x-mister-cartoon.server.tsx, src/routes/collections/suavecito-x-violent-gentlemen.server.tsx
- added routes for collaboration collections, shows variant instead of product item
- added images for the new collaborations in collaborations page
=> added new collab pages and routes

src/components/analytics/ProductViewEvent.client.tsx, src/components/cart/CartFreeGiftWithPurchase.client.tsx, src/lib/gtm.ts, src/types/gtm.d.ts
=> Added GA4 Custom Events

src/components/analytics/ProductViewEvent.client.tsx
- Added legacy resource id to event payload
=> Updated Event Payload with legacy resource id

src/components/collection/FeaturedBanner.server.tsx, src/data/collection-featured-banners.ts, src/routes/collections/mens-hair.server.tsx, src/routes/pages/contact.server.tsx, src/styles/suavecito.css
added hair treatment products to mens-hair collection, updated tables
=> Hair treatment

src/components/collection/ProductImageCarousel.client.tsx, src/components/global/FooterMenu.client.tsx, src/data/collection-data.ts, src/routes/pages/about-us.server.tsx
- added translated about us page
- made minor styling changes
=> added translated about-page

src/data/home-page-es.ts, src/routes/index.server.tsx
swapped home page video to be spanish version
=> swapped home page video

src/components/sections/Banner.tsx, src/data/free-gift-with-purchase.ts, src/data/home-page-es.ts, src/data/pomade-blog-es-old.ts, src/data/pomade-blog-es.ts, src/data/suavecita-page-es.ts
- Updated FGWP items / Banners
- Updated Pomade Blog Translations
=> Deploy staging

src/components/AppWrapper.server.tsx, src/components/FreeGiftProvider/FreeGiftProvider.client.tsx, src/components/FreeGiftProvider/constants.ts, src/components/FreeGiftProvider/context.client.tsx, src/components/FreeGiftProvider/types.ts, src/components/collection/CollectionImageCarousel.client.tsx, src/components/collection/index.ts, src/components/sections/FreeGiftWithPurchaseProgressBar.client.tsx, src/components/sections/ThreeImageBanner.server.tsx, src/components/sections/index.server.ts, src/components/sections/index.ts, src/components/templates/collection-best-sellers.server.tsx, src/components/templates/index.server.ts, src/data/collection-best-sellers.ts, src/data/free-gift-with-purchase.ts, src/routes/collections/best-sellers.server.tsx
- Added Best Sellers Collection Template
- Moved FGWP consts to data dir
=> Best sellers

src/components/product/ProductOptionsVariantForm.client.tsx, src/components/sections/AnnouncementBanner.server.tsx, src/data/home-page-es.ts
- Product Template - Sold Out -> Agotado
- Home Page - Announcement
- Home Page - Banner
=> Recommended translations from mx

src/components/templates/product-kit-item-template.server.tsx, src/components/templates/product-metafield-colors-get-inspired-template.server.tsx, src/components/templates/product-metafield-get-inspired-template.server.tsx, src/components/templates/product-metafield-pomade-template.server.tsx, src/components/templates/product-metafield-spb-beard-oils-template.server.tsx, src/components/templates/product-metafield-spb-template.server.tsx, src/components/templates/product-metafield-template.server.tsx, src/components/templates/product-template.server.tsx
- Updated userServerAnalytics with products
- Removed class `format` from product headings / titles
=> Update product analytics

README.md, src/components/AppWrapper.server.tsx, src/components/FreeGiftCardProvider/FreeGiftCardProvider.client.tsx, src/components/FreeGiftCardProvider/context.client.tsx, src/components/FreeGiftCardProvider/hooks.client.tsx, src/components/FreeGiftCardProvider/index.ts, src/components/FreeGiftCardProvider/types.ts, src/components/cart/CartLineItem.client.tsx, src/data/free-gift-card-with-purchase.ts, src/data/free-gift-with-purchase.ts, src/data/home-page-es.ts
- Added Free Gift Card with Purchase Provider
- Updated Home Page Banner
=> Free Gift Card W/ Purchase

src/components/elements/Badge.tsx, src/components/product/ProductOptionsVariantForm.client.tsx, src/components/templates/product-kit-item-template.server.tsx, src/components/templates/product-metafield-colors-get-inspired-template.server.tsx, src/components/templates/product-metafield-get-inspired-template.server.tsx, src/components/templates/product-metafield-pomade-template.server.tsx, src/components/templates/product-metafield-spb-beard-oils-template.server.tsx, src/components/templates/product-metafield-spb-template.server.tsx, src/components/templates/product-metafield-template.server.tsx, src/components/templates/product-template.server.tsx, src/lib/suavecito-fragments.ts
- Updated Sale Badge to use new BOGO & B2G1F metafields
=> Update sale badge

src/components/product/ProductSectionKitIncludes.server.tsx, src/components/templates/product-kit-item-template.server.tsx, src/routes/products/beard-balm.server.tsx, src/routes/products/lip-gloss.server.tsx, src/routes/products/mustache-wax.server.tsx, src/routes/products/suavecita-lipstick.server copy.tsx, src/routes/products/suavecita-lipstick.server.tsx
changes to support the addition of the following products: 
- OG Shampoo
- OG Conditioner
- OG Shampoo & Conditioner Set
- Beard Wash Kit
- Beard Balm
- Mustache Wax
- Shave Gel
- Pre-Shave Oil
- Shave Kit
- Deodorant
- Lip Gloss
- Tinted Brow Gel
- Brow Pomade
- Eyebrow Pomade Pencil
- Matte Lipstick
- Shine Spray
=> Add translated products

src/lib/utils.ts
=> Fix internal link

src/components/product/ProductOptionsVariantForm.client.tsx, src/components/templates/product-template.server.tsx, src/hooks/useFilterExcludedVariants.tsx, src/routes/products/body-soap.server.tsx
Patched useFilterExcludedVariants hook
=> Updated `useFilterExcludedVariants` hook

src/data/discounts.ts
=> rm-discount

.github/workflows/oxygen-deployment-131155.yml, src/components/AppWrapper.server.tsx, src/data/free-gift-with-purchase.ts, src/data/home-page/home-page-es-december.ts, src/data/home-page/home-page-es-january.ts, src/data/home-page/home-page-es.ts
Updated Node to v18 in GitHub Action due to failed deployment. Updated FGWP to not render based on flag.
=> App wrapper disable fgwp
